# Generated by Django 4.2.5 on 2023-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='immagine',
            field=models.ImageField(upload_to='uploaded_fighters/'),
        ),
    ]
